### ISSUE TITLE
SPIClass support for ESP32

### ISSUE THREAD

**Issue by ElcRcp** [adafruit/SdFat#17]
**Is your feature request related to a problem? Please describe.**
Hello, I'm using an esp32 wrover board to do some sensor readings and logging in SDcard. I normally use standart SD library but recently I bought an 128GB SDCard and since it is exFat I needed an exFat driver and found this library. Thing is, I Use 4 SPI sensors which are share common clock and data lines and 1 SD card which uses seperate set of clk and data lines. I use VSPI SPICLASS to define them and start SD card using SD.begin(uint8_t ssPin, SPIClass &spi, uint32_t frequency). Unfortunately I couldn't find any options in SdFat library to start SD with a defined SPI class which is very necessary if u are using VSPI.

**Describe the solution you'd like**
It would be very useful for ESP32 boards if this library had a begin() option for SPIClass

**Describe alternatives you've considered**
I tried to use SoftwareSpi, it didnt even compile for ESP32

I'm actually not even sure anymore if this library supports esp32 even it says it is in the library properties.

**Comment by mhaberler** [comment]
I'm using this library just fine with an esp32-s3:

`````
#define SD_CONFIG SdSpiConfig(SD_CS_PIN, SHARED_SPI, SPI_CLOCK)

SdFat fs;
...
  // https://github.com/espressif/esp-idf/blob/master/examples/storage/sd_card/sdspi/README.md#pin-assignments
  SPI.begin(36, 37, 35, 34);
  fs.begin(SD_CONFIG)
`````
